Custom lint tests
leancodepl/flutter_corelibrary pull request #150
Opened 2023-08-30 14:06 UTC by KamilSztandur

2023-08-30 14:07 UTC, PiotrRogulski commented on packages/leancode_lint/test/lints_test_app/pubspec.yaml
> +  uses-material-design: true
Add a final newline

2023-08-30 14:10 UTC, PiotrRogulski commented on packages/leancode_lint/test/lints_test_app/analysis_options.yaml
> +    - custom_lint
Ditto

2023-08-30 14:18 UTC, PiotrRogulski approved these changes

2023-08-30 14:23 UTC, shilangyu commented on packages/leancode_lint/test/lints_test_app/lib/use_design_system_item_test.dart
add test case for merely referencing a forbidden type. For example:


```dart
void func(
	Text text,
) {}
```

`Text` here should be linted

2023-08-30 14:24 UTC, shilangyu commented on packages/leancode_lint/test/lints_test_app/pubspec.yaml
> +description: Simple Flutter app for lint rules testing
```suggestion
description: Flutter app for lint rules testing
```

2023-08-30 14:24 UTC, shilangyu commented on packages/leancode_lint/test/lints_test_app/pubspec.yaml
> +    sdk: flutter
not needed

2023-08-30 14:58 UTC, shilangyu commented on packages/leancode_lint/README.md
revert all changes

2023-08-31 15:14 UTC, shilangyu requested changes
.dart_tool is in .gitignore, I am not sure how you pushed it

2023-08-31 15:14 UTC, shilangyu commented on .github/workflows/leancode_lint-test.yml
> +        run: cd test/lints_test_app/ && flutter pub get && dart run custom_lint
```suggestion
      - name: Run lint rules tests
        working-directory: test/lints_test_app
        run: |
          flutter pub get
          dart run custom_lint
```

2023-08-31 15:14 UTC, shilangyu commented on packages/leancode_lint/test/lints_test_app/lib/add_sliver_prefix_for_widget_returning_sliver_test.dart
> +// Should not throw warning since it's prefixed
For the future: warnings arent thrown. Either reported or raised.

2023-08-31 16:21 UTC, shilangyu approved these changes

2023-08-31 17:28 UTC, merged