Fix custom lint: constructor parameters and fields should have the same order
leancodepl/flutter_corelibrary pull request #328
Opened 2024-07-23 16:38 UTC by karolinaoparczyk

Changes how `constructor_parameters_and_fields_should_have_the_same_order` reports issues.

Right now the issue is reported just above the first parameter, which doesn't always cause the problem. In my opinion it would be better if the lint reported issues above the constructor.
This is especially confusing when one wants to use `ignore`:

How it looks now:
```
class MyClass{
    MyClass({
        // ignore: constructor_parameters_and_fields_should_have_the_same_order
        required this.value,
        required this.label,
        required this.enabled,
    });

    final bool enabled;
    final double value;
    final String label;
}
```

How it looks after my changes:
```
class MyClass{
    // ignore: constructor_parameters_and_fields_should_have_the_same_order
    MyClass({
        required this.value,
        required this.label,
        required this.enabled,
    });

    final bool enabled;
    final double value;
    final String label;
}
```

2024-07-24 08:27 UTC, gogolon approved these changes

2024-07-24 08:34 UTC, PiotrRogulski approved these changes

2024-07-25 10:36 UTC, shilangyu approved these changes

2024-07-25 10:37 UTC, shilangyu requested changes
Please add a changelog entry

2024-07-25 10:38 UTC, shilangyu approved these changes

2024-08-04 18:58 UTC, shilangyu commented
Can we merge this?

2024-08-05 09:14 UTC, merged