Add melos configuration
leancodepl/flutter_corelibrary pull request #34
Opened 2021-09-16 10:41 UTC by RobertOdrowazLNCD

2021-09-16 10:51 UTC, Albert221 approved these changes

2021-09-23 09:28 UTC, mateuszwojtczak requested changes

2021-09-23 09:28 UTC, mateuszwojtczak commented on melos.yaml
> +name: LeanCode flutter corelibrary
LeanCode Flutter Core Library

2021-09-23 09:40 UTC, mateuszwojtczak approved these changes

2021-09-23 09:43 UTC, merged