Add 2.0.4 login_client
leancodepl/flutter_corelibrary pull request #39
Opened 2021-11-19 10:14 UTC by shilangyu

2021-11-19 10:17 UTC, Albert221 commented on packages/login_client/CHANGELOG.md
> +- `onCredentialsChanged` now yields events after they have completed.
```suggestion
- `onCredentialsChanged` now yields **after** the credentials have changed (in the storage).
```

2021-11-19 10:18 UTC, Albert221 requested changes
Just a small change clarification

2021-11-22 16:11 UTC, mkucharski17 approved these changes

2021-11-22 16:27 UTC, lukaszgarstecki approved these changes

2021-11-24 10:07 UTC, Albert221 approved these changes

2021-11-24 10:11 UTC, merged